/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Contable.Vistas;

import Contable.Controladores.Conexion;
import Contable.Modulos.CRUD_Cuenta;
import static Contable.Modulos.CRUD_Cuenta.listaCuenta;
import Contable.Modulos.CRUD_Partidas;
import static Contable.Modulos.CRUD_Partidas.listaPartidas;
import Contable.Modulos.PDF_LibroDiario_BalanceGeneral;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ulise
 */
public class JFMostrar_LibroDiaro extends javax.swing.JFrame {
    CRUD_Partidas CRPartidas = new CRUD_Partidas();
    CRUD_Cuenta CRCuenta = new CRUD_Cuenta();
    PDF_LibroDiario_BalanceGeneral libroDiario_BalanceGeneral = new PDF_LibroDiario_BalanceGeneral();
    DefaultTableModel model;
    public String ID_LibroDato;
    int fila;
    /**
     * Creates new form JFMostrar_CuentasLibroDiarop
     */
    public JFMostrar_LibroDiaro(String ID_Libro) {
        initComponents();
        this.setLocationRelativeTo(null);
        
        ID_LibroDato = ID_Libro;
        model = (DefaultTableModel) this.TablePartida.getModel();
        Llenar(ID_Libro);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablePartida = new javax.swing.JTable();
        TxtTotalDebe = new javax.swing.JLabel();
        TxtTotalHaber = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtnMosLibrosDiarios = new javax.swing.JButton();
        BtnNuevaPartida = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        TablePartida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Fecha", "Cuenta", "Debe", "Haber"
            }
        ));
        jScrollPane1.setViewportView(TablePartida);
        if (TablePartida.getColumnModel().getColumnCount() > 0) {
            TablePartida.getColumnModel().getColumn(0).setMinWidth(100);
            TablePartida.getColumnModel().getColumn(0).setPreferredWidth(100);
            TablePartida.getColumnModel().getColumn(0).setMaxWidth(100);
            TablePartida.getColumnModel().getColumn(1).setMinWidth(150);
            TablePartida.getColumnModel().getColumn(1).setPreferredWidth(150);
            TablePartida.getColumnModel().getColumn(1).setMaxWidth(150);
            TablePartida.getColumnModel().getColumn(3).setMinWidth(100);
            TablePartida.getColumnModel().getColumn(3).setPreferredWidth(100);
            TablePartida.getColumnModel().getColumn(3).setMaxWidth(100);
            TablePartida.getColumnModel().getColumn(4).setMinWidth(100);
            TablePartida.getColumnModel().getColumn(4).setPreferredWidth(100);
            TablePartida.getColumnModel().getColumn(4).setMaxWidth(100);
        }

        TxtTotalDebe.setText("TOTAL DEBE");

        TxtTotalHaber.setText("TOTAL HABER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(TxtTotalDebe)
                        .addGap(51, 51, 51)
                        .addComponent(TxtTotalHaber)
                        .addGap(39, 39, 39))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtTotalHaber)
                    .addComponent(TxtTotalDebe))
                .addGap(14, 14, 14))
        );

        jPanel2.setBackground(new java.awt.Color(0, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("LIBRO DIARIO");

        BtnMosLibrosDiarios.setText("REGRESAR");
        BtnMosLibrosDiarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMosLibrosDiariosActionPerformed(evt);
            }
        });

        BtnNuevaPartida.setText("Nueva Partida");
        BtnNuevaPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNuevaPartidaActionPerformed(evt);
            }
        });

        BtnEliminar.setText("Eliminar");
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        jButton1.setText("Generar PDF");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(307, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(129, 129, 129))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(BtnMosLibrosDiarios)
                        .addGap(77, 77, 77)
                        .addComponent(BtnNuevaPartida)
                        .addGap(83, 83, 83)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addComponent(BtnEliminar)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnNuevaPartida)
                    .addComponent(BtnEliminar)
                    .addComponent(jButton1)
                    .addComponent(BtnMosLibrosDiarios))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnMosLibrosDiariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMosLibrosDiariosActionPerformed
        // TODO add your handling code here:
        //OBJETO PARA INTERACTUAR CON EL JFMostrar_Detalle
        JFMostrar_InformeLibros Mostrar = new JFMostrar_InformeLibros();
        //SE INDICA QUE SE MUESTRE LA VENTANA
        Mostrar.setVisible(true);
        //SE OCULTA LA VENTANA ACTUAL
        this.dispose();
    }//GEN-LAST:event_BtnMosLibrosDiariosActionPerformed

    private void BtnNuevaPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNuevaPartidaActionPerformed
        // TODO add your handling code here:

        //OBJETO PARA INTERACTUAR CON EL JFCrear_InContable
        JFCrear_Partida Mostrar = new JFCrear_Partida(ID_LibroDato);
        //SE INDICA QUE SE MUESTRE LA VENTANA
        Mostrar.setVisible(true);
        //SE OCULTA LA VENTANA ACTUAL
        this.dispose();

    }//GEN-LAST:event_BtnNuevaPartidaActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        // TODO add your handling code here:
        int fila = TablePartida.getSelectedRow();
        int ID = 0;
        
        if(fila == -1){
            JOptionPane.showMessageDialog(null, "NO SE A SELECIONADO FILA");
        }
        else{
            
            ID = Integer.parseInt((String) TablePartida.getValueAt(fila, 0).toString());
            
            CRUD_Partidas.EliminarPorPartida(ID);
        }
        
        Llenar(ID_LibroDato);
    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        libroDiario_BalanceGeneral.PDFLibroDiario(ID_LibroDato);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    public void Llenar(String ID_Libro){
        int contador = 1;
        double TotalDebe = 0;
        double TotalHaber = 0;
        
        //SE LIMPIA LA TABLA
        model.setRowCount(0);
        //SE LLENA EL ARREGLO CON LOS VALORES DE LA TABLA
        CRPartidas.LlenarTabla();
        CRCuenta.LlenarTabla();
        
        //CICLO PARA LLENAR LA TABLA CON LOS VALORES DEL ARREGLO
        for(int PosPartida = 0; PosPartida < listaPartidas.size(); PosPartida++){
            
            if(listaPartidas.get(PosPartida).getIDLibro() == Integer.valueOf(ID_Libro)){
                
                System.err.println(""+listaPartidas.get(PosPartida).getID());
                
                model.addRow(new Object[]{listaPartidas.get(PosPartida).getID(),
                                    listaPartidas.get(PosPartida).getFecha(),
                                    "Partida "+contador,"",""});
                
                for(int PosCuenta = 0; PosCuenta < listaCuenta.size(); PosCuenta++){
                    
                    if(listaCuenta.get(PosCuenta).getIDPartida() == listaPartidas.get(PosPartida).getID()){
                        
                        if("DEBE".equals(listaCuenta.get(PosCuenta).getTipoMovimiento())){
                            model.addRow(new Object[]{"","",
                                listaCuenta.get(PosCuenta).getNombreCuenta(),
                                listaCuenta.get(PosCuenta).getMonto(),""});
                            
                            TotalDebe = TotalDebe+listaCuenta.get(PosCuenta).getMonto();
                            
                        }
                        else if("HABER".equals(listaCuenta.get(PosCuenta).getTipoMovimiento())){
                            model.addRow(new Object[]{"","",
                                listaCuenta.get(PosCuenta).getNombreCuenta(),
                                "",listaCuenta.get(PosCuenta).getMonto()});
                            
                            TotalHaber = TotalHaber+listaCuenta.get(PosCuenta).getMonto();
                        }
                        
                    }
                    
                }
                
                model.addRow(new Object[]{listaPartidas.get(PosPartida).getID(),
                                    listaPartidas.get(PosPartida).getFecha(),
                                    listaPartidas.get(PosPartida).getConcepto(),
                                     "",""});
                
                model.addRow(new Object[]{});
                
                contador++;
            }
            
        }
        
        TxtTotalDebe.setText("Total Debe: "+ String.valueOf(TotalDebe));
        TxtTotalHaber.setText("Total Haber: "+ String.valueOf(TotalHaber));
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMostrar_LibroDiaro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMostrar_LibroDiaro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMostrar_LibroDiaro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMostrar_LibroDiaro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                //OBJETO PARA ENTERACTUAR CON LA CONEXION
                Conexion conec = new Conexion();
                //CREA REALIZA LA CONEXION Y CREA LA TABLA SI NO HAY
                conec.CrearTablas();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnMosLibrosDiarios;
    private javax.swing.JButton BtnNuevaPartida;
    private javax.swing.JTable TablePartida;
    private javax.swing.JLabel TxtTotalDebe;
    private javax.swing.JLabel TxtTotalHaber;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
